pub mod build_search_url;
mod constants;
pub mod course_details_scraper;
pub mod course_scraper;
pub mod courses_data_scraper;
mod extract_exam_info;
pub mod fetch;
mod parser;
mod selector;
mod utils;
